version: '3.8'

services:
  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081
      - TRANSACTION_SERVICE_URL=http://transaction-service:8082
      - AUTH_SERVICE_URL=http://auth-service:8083
    networks:
      - bank-network
    restart: always

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8082
      - ACCOUNT_SERVICE_URL=http://account-service:8081
      - NOTIFICATION_SERVICE_URL=http://notification-service:8084
    networks:
      - bank-network
    restart: always

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8083
      - USER_SERVICE_URL=http://user-service:8085
    networks:
      - bank-network
    restart: always

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8084
    networks:
      - bank-network
    restart: always

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8085
    networks:
      - bank-network
    restart: always

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9999:9999"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=9999
      - ACCOUNT_SERVICE_URL=http://account-service:8081
      - TRANSACTION_SERVICE_URL=http://transaction-service:8082
      - AUTH_SERVICE_URL=http://auth-service:8083
      - NOTIFICATION_SERVICE_URL=http://notification-service:8084
      - USER_SERVICE_URL=http://user-service:8085
    networks:
      - bank-network
    restart: always
    depends_on:
      - account-service
      - transaction-service
      - auth-service
      - notification-service
      - user-service

networks:
  bank-network:
    driver: bridge